### ISSUE TITLE
Error: Puppet::Parser::AST::Resource

### ISSUE THREAD

**Issue by youssfisebti** [pedroamador/ubuntu1404-mongodb26#5]
Error: Could not find declared class ::mongodb::globals at /tmp/vagrant-puppet-3/manifests/default.pp:11 on node ubuntumongo
the class is not defined what ca i do

**Comment by youssfisebti** [comment]
I follow your documentation but i have this error !!
 ubuntumongo: Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find declared class ::mongodb::globals at /tmp/vagrant-puppet-3/manifests/default.pp:18 on node ubuntumongo

**Comment by pedroamador** [comment]
Maybe you've cloned the repo whitout "--recursive" option?

    $ git clone --recursive https://github.com/pedroamador/ubuntu1404-mongodb26

The puppet modules was linked as git submodules. You can fix your local copy  with

    $ git submodule init
    [...]
    $ git submodule update
    [...]
